doctrine_migrations:
    migrations_paths:
        'MobilityWork\Infrastructure\Persistence\Doctrine\DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/DoctrineMigrations'
    enable_profiler: false
