name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v5
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      # - 
      #   name: Debug Healthcheck
      #   run: docker compose exec php curl -v http://localhost:2019/metrics

      -
        name: Start services
        run: docker compose up --wait --no-build || true
      -
        name: Print PHP Logs
        run: docker compose logs php || true
      -
        name: Print Docker Compose ps
        run: docker compose ps || true
      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
      -
        name: Check HTTPS reachability
        run: curl -vk --fail-with-body https://localhost
      -
        name: Create test database
        run: docker compose exec -T php bin/console -e test doctrine:database:create
      -
        name: Run migrations
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      # -
      #   name: Security check
      #   run: docker compose exec -T php symfony check:security
      -
        name: Run PHPUnit
        run: docker compose exec -T php bin/phpunit
      -
        name: Run CS Fixer
        run: docker compose exec -T php vendor/bin/php-cs-fixer fix
      -
        name: Run PHPStan
        run: docker compose exec -T php vendor/bin/phpstan analyse src --level=9 --memory-limit=256M
      -
        name: YAML linter
        run: docker compose exec -T php bin/console lint:yaml .
      -
        name: Doctrine Schema Validator
        run: docker compose exec -T php bin/console -e test doctrine:schema:validate --skip-sync
      # Temporary fix for the following problem:
      # doctrine:schema:validate -> [ERROR] The database schema is not in sync with the current mapping file.
      # doctrine:schema:update --dump-sql -> DROP TABLE doctrine_migration_versions;
      -
        name: Validating database schema sync
        run: |
          output=$(docker compose exec -T php bin/console doctrine:schema:update --dump-sql)
          if [[ "$output" = 'DROP TABLE doctrine_migration_versions;' ]]; then
            echo 'OK'
          fi

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0